services:
  dtek-telegram-bot:
    image: ghcr.io/ndmik-dev/light-finder:latest
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/db/app.db
    ports:
      - "8080:8080"
    volumes:
      - /opt/dtek-telegram-bot/db:/app/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
