services:
  dtek-telegram-bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/db/app.db
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
