services:
  firefly:
    image: ghcr.io/ndmik-dev/firefly:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_CHAT_IDS: ${TELEGRAM_ADMIN_CHAT_IDS}
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/db/app.db
    expose:
      - "8080"
    volumes:
      - /opt/firefly/db:/app/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
