services:
  firefly:
    image: ghcr.io/ndmik-dev/firefly:latest
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/db/app.db
    ports:
      - "8080:8080"
    volumes:
      - /opt/firefly/db:/app/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
