spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: dtek-telegram-bot
  datasource:
    url: jdbc:sqlite:src/main/resources/db/app.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  task:
    scheduling:
      time-zone: Europe/Kyiv

server:
  port: 8080

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}

scheduler:
  shutdowns:
    fixed-delay-ms: 10
