spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    time-zone: Europe/Kyiv
  servlet:
    multipart:
      enabled: false
  application:
    name: firefly
  datasource:
    url: jdbc:sqlite:src/main/resources/db/app.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        jdbc:
          time_zone: Europe/Kyiv
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  admin-chat-ids: ${TELEGRAM_ADMIN_CHAT_IDS:}

scheduler:
  shutdowns:
    fixed-delay-ms: 10
    time-zone: Europe/Kyiv

yasno:
  lookup:
    enabled: false
    region-id: 25
    dso-id: 902
    street-query: ""
    house-query: ""
